# pnpm-workspace.yml
# We use pnpm to configures multi-package workspace project.
# This file lists all packages in project
# Author: Ke An Nguyen
packages:
  - 'packages/backend'   # Package contains backend code
  - 'packages/frontend'  # Package contains frontend code
  - 'packages/shared-utils' # Package contains shared-utils utils, shared-utils type (API request type) for backend & frontend
  - 'packages/shared-models' # Package contains models of application